apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: docker.io/saiut/handson-ci-image:6bc08815ca9fd818024619e2d4ae0489e5004c1d
        name: blue
        ports:
          - containerPort: 80
